/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "bg-green-100",
    "text-green-800",
    "border-green-200",
    "bg-green-500",
    "bg-blue-100",
    "text-blue-800",
    "border-blue-200",
    "bg-blue-500",
    "bg-orange-100",
    "text-orange-800",
    "border-orange-200",
    "bg-orange-500",
    "bg-purple-100",
    "text-purple-800",
    "border-purple-200",
    "bg-purple-500",
    "bg-pink-100",
    "text-pink-800",
    "border-pink-200",
    "bg-pink-500",
    "bg-red-100",
    "text-red-800",
    "border-red-200",
    "bg-red-500",
    "bg-yellow-100",
    "text-yellow-800",
    "border-yellow-200",
    "bg-yellow-500",
    "bg-teal-100",
    "text-teal-800",
    "border-teal-200",
    "bg-teal-500",
    "bg-indigo-100",
    "text-indigo-800",
    "border-indigo-200",
    "bg-indigo-500",
    "bg-cyan-100",
    "text-cyan-800",
    "border-cyan-200",
    "bg-cyan-500",
    "bg-gray-100",
    "text-gray-800",
    "border-gray-200",
    "bg-gray-500",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
